export const XFLOWS_ICONS = {
  input: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 12h12"/><path d="M12 8l4 4-4 4"/><circle cx="20" cy="12" r="1.5" fill="currentColor"/></svg>',
  output: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="4" cy="12" r="1.5" fill="currentColor"/><path d="M8 12h12"/><path d="M16 8l4 4-4 4"/></svg>',
  prompt: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 4h16v12H8l-4 4z"/><path d="M8 9h8M8 12h5"/></svg>',
  openai: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 2a4 4 0 0 0-3.46 6 4 4 0 0 0 0 8 4 4 0 0 0 6.92 0 4 4 0 0 0 0-8A4 4 0 0 0 12 2z"/><path d="M12 8v8M8 10l8 4M16 10l-8 4" stroke-width="1.2"/></svg>',
  anthropic: '<svg viewBox="0 0 24 24" fill="currentColor"><path d="M7 4l-4 16h3l1-4h6l1 4h3L13 4H7zm0 8l2-6 2 6H7zm10-8l4 16h-3l-4-16h3z"/></svg>',
  http: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c2.5 3 2.5 15 0 18M12 3c-2.5 3-2.5 15 0 18"/></svg>',
  search: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="6"/><path d="M20 20l-4.5-4.5"/></svg>',
  code: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M8 8l-4 4 4 4M16 8l4 4-4 4M14 6l-4 12"/></svg>',
  vector: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><ellipse cx="12" cy="6" rx="8" ry="3"/><path d="M4 6v6c0 1.7 3.6 3 8 3s8-1.3 8-3V6"/><path d="M4 12v6c0 1.7 3.6 3 8 3s8-1.3 8-3v-6"/></svg>',
  sum: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 4h14L11 12l8 8H5l8-8L5 4z"/></svg>',
  branch: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="6" cy="6" r="2"/><circle cx="6" cy="18" r="2"/><circle cx="18" cy="12" r="2"/><path d="M8 6c0 4 8 4 8 6M8 18c0-4 8-4 8-6"/></svg>',
  json: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M8 4c-2 0-3 1-3 3v3c0 1-1 2-2 2 1 0 2 1 2 2v3c0 2 1 3 3 3M16 4c2 0 3 1 3 3v3c0 1 1 2 2 2-1 0-2 1-2 2v3c0 2-1 3-3 3"/></svg>',
  regex: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 4v8M8.5 6l7 4M8.5 10l7-4"/><circle cx="6" cy="18" r="2" fill="currentColor"/></svg>',
  agent: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="6" y="8" width="12" height="10" rx="2"/><path d="M12 4v4M9 12v2M15 12v2"/><circle cx="3" cy="13" r="1.5"/><circle cx="21" cy="13" r="1.5"/></svg>',
  markdown: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="6" width="18" height="12" rx="2"/><path d="M7 14V10l2 3 2-3v4M15 10v4M13 12l2 2 2-2"/></svg>',
  trace: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="3"/><circle cx="12" cy="12" r="8"/><path d="M12 4v2M12 18v2M4 12h2M18 12h2"/></svg>',
  guard: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 3l8 3v6c0 5-4 8-8 9-4-1-8-4-8-9V6l8-3z"/><path d="M9 12l2 2 4-4"/></svg>',
};

export const XFLOWS_CATALOG = [
  { id: "Input", name: "Input", category: "I/O", kind: "input", icon: "input", desc: "User input - entry point of the workflow.", params: [] },
  { id: "Output", name: "Output", category: "I/O", kind: "output", icon: "output", desc: "Final response shown to the user.", params: [] },
  {
    id: "PromptTemplate",
    name: "Prompt",
    category: "Prompt",
    kind: "transform",
    icon: "prompt",
    desc: "Render a prompt by substituting {input} with the upstream value.",
    params: [
      { name: "template", type: "textarea", default: "Answer concisely:\n\n{input}" },
      { name: "system", type: "textarea", default: "You are a helpful assistant." },
    ],
  },
  {
    id: "LLM",
    name: "LLM",
    category: "LLM",
    kind: "container",
    icon: "agent",
    desc: "LLM block - drop a provider inside it.",
    accepts: ["LLM-Provider"],
    configs: [
      { name: "tracer", label: "tracer", accepts: ["Observability"] },
      { name: "memory", label: "memory", accepts: ["Memory"] },
      { name: "tools", label: "tools", accepts: ["Tool"] },
    ],
    params: [],
  },
  {
    id: "OpenAIChat",
    name: "OpenAI",
    category: "LLM-Provider",
    kind: "provider",
    icon: "openai",
    requiresContainer: "LLM",
    desc: "Call OpenAI chat model through backend routing.",
    params: [
      { name: "model", type: "select", options: ["gpt-4o-mini", "gpt-4o", "gpt-4-turbo"], default: "gpt-4o-mini" },
      { name: "temperature", type: "number", default: 0.7, step: 0.1 },
      { name: "max_tokens", type: "number", default: 512 },
    ],
  },
  {
    id: "AnthropicChat",
    name: "Claude",
    category: "LLM-Provider",
    kind: "provider",
    icon: "anthropic",
    requiresContainer: "LLM",
    desc: "Call Anthropic model through backend routing.",
    params: [
      { name: "model", type: "select", options: ["claude-haiku-4-5", "claude-sonnet-4-5", "claude-opus-4"], default: "claude-haiku-4-5" },
      { name: "temperature", type: "number", default: 0.7, step: 0.1 },
      { name: "max_tokens", type: "number", default: 1024 },
    ],
  },
  {
    id: "HttpRequest",
    name: "HTTP",
    category: "Tool",
    kind: "tool",
    icon: "http",
    desc: "Make an HTTP GET/POST request.",
    params: [
      { name: "method", type: "select", options: ["GET", "POST"], default: "GET" },
      { name: "url", type: "text", default: "https://api.example.com/data" },
      { name: "body_uses_input", type: "bool", default: true },
    ],
  },
  { id: "WebSearch", name: "Search", category: "Tool", kind: "tool", icon: "search", desc: "Search tool wrapper.", params: [{ name: "top_k", type: "number", default: 3 }] },
  { id: "CodeExec", name: "Code", category: "Tool", kind: "tool", icon: "code", desc: "Execute code in backend sandbox.", params: [{ name: "code", type: "textarea", default: "return input.toUpperCase();" }] },
  {
    id: "VectorStore",
    name: "Vector DB",
    category: "Memory",
    kind: "aux",
    icon: "vector",
    desc: "Vector retrieval - attach to LLM as memory.",
    params: [
      { name: "collection", type: "text", default: "docs" },
      { name: "top_k", type: "number", default: 3 },
      { name: "query", type: "text", default: "" },
    ],
  },
  { id: "Summarizer", name: "Summarize", category: "Memory", kind: "transform", icon: "sum", desc: "Condense input by max chars.", params: [{ name: "max_chars", type: "number", default: 200 }] },
  {
    id: "IfElse",
    name: "If/Else",
    category: "Router",
    kind: "router",
    icon: "branch",
    desc: "Contains-check with warn/fail modes.",
    params: [
      { name: "contains", type: "text", default: "" },
      { name: "mode", type: "select", options: ["warn", "fail"], default: "warn" },
    ],
  },
  { id: "JsonParser", name: "JSON", category: "Parser", kind: "transform", icon: "json", desc: "Parse upstream text as JSON.", params: [{ name: "extract_path", type: "text", default: "" }] },
  {
    id: "RegexExtract",
    name: "Regex",
    category: "Parser",
    kind: "transform",
    icon: "regex",
    desc: "Extract first regex match group.",
    params: [
      { name: "pattern", type: "text", default: "\\d+" },
      { name: "flags", type: "text", default: "i" },
    ],
  },
  {
    id: "ReActAgent",
    name: "ReAct",
    category: "Agent",
    kind: "llm",
    icon: "agent",
    desc: "Agent loop through backend orchestration.",
    params: [
      { name: "max_steps", type: "number", default: 3 },
      { name: "tools", type: "text", default: "search,calculator" },
    ],
  },
  {
    id: "Markdown",
    name: "Markdown",
    category: "Format",
    kind: "transform",
    icon: "markdown",
    desc: "Wrap content in markdown.",
    params: [{ name: "wrap", type: "select", options: ["as-is", "codeblock", "quote", "bullets"], default: "as-is" }],
  },
  {
    id: "Tracer",
    name: "Tracer",
    category: "Observability",
    kind: "aux",
    icon: "trace",
    desc: "Attach to LLM tracer config.",
    params: [
      { name: "level", type: "select", options: ["info", "debug", "verbose"], default: "info" },
      { name: "destination", type: "select", options: ["console", "trace-panel", "both"], default: "both" },
    ],
  },
  {
    id: "Guardrail",
    name: "Guardrail",
    category: "Observability",
    kind: "aux",
    icon: "guard",
    desc: "Guard checks attached to LLM tracing.",
    params: [{ name: "forbidden", type: "text", default: "password,secret" }],
  },
];

export const CATEGORY_COLORS = {
  "I/O": { fg: "#1f2937", bg: "#f1f5f9", dot: "#475569" },
  Prompt: { fg: "#6b3aa0", bg: "#f3eafd", dot: "#8b5cf6" },
  LLM: { fg: "#0f766e", bg: "#e6fbf6", dot: "#14b8a6" },
  "LLM-Provider": { fg: "#0f766e", bg: "#ccfbf1", dot: "#0d9488" },
  Tool: { fg: "#9a3412", bg: "#fff1e6", dot: "#f97316" },
  Memory: { fg: "#1e40af", bg: "#e8efff", dot: "#3b82f6" },
  Router: { fg: "#854d0e", bg: "#fef7c8", dot: "#eab308" },
  Parser: { fg: "#155e75", bg: "#e3f6fb", dot: "#06b6d4" },
  Agent: { fg: "#9f1239", bg: "#ffe9ee", dot: "#e11d48" },
  Format: { fg: "#475569", bg: "#eef2f7", dot: "#64748b" },
  Observability: { fg: "#7c2d12", bg: "#fef3e2", dot: "#c2410c" },
};
